language: android

jdk: oraclejdk8

android:
  components:
  - platform-tools             # ADB (디바이스 또는 에뮬레이터와 통신) 포함
  - tools                      # 실제 안드로이드 SDK
  - build-tools-25.0.2         # 빌드 툴 버전
  - android-25                 # 타겟 버전
  - extra-android-m2repository # 안드로이드에서 제공하는 라이브러리

licenses:
    # Check licenses: http://docs.travis-ci.com/user/languages/android/#Dealing-with-Licenses
    # By default Travis will accept all the licenses, but it's also possible to define a white list:
    # White list current android-sdk-license revision.
    # - 'android-sdk-license-5be876d5'
    # White list all android-sdk-license revisions.
    # - 'android-sdk-license-.+'
    # White list all the licenses.
    - '.+'

before_install:
  - chmod +x gradlew

script: ./gradlew build